const initPropetiesExtra = {

    jacket: {
        index: {
            default_lot_ao_vest_tren: [0],
            default_lot_ao_vest_duoi: [0],
            lot_ao_vest_tren: [0],
            lot_ao_vest_duoi: [0],
            lot_ao_vest_unlined_tren: [0],
            lot_ao_vest_unlined_duoi: [0],
            unlined_top_x: [0],
            unlined_top: [0],
            unlined_bottom: [0],
            khan_tui_nguc: [0],
            vong_co_sau_ao: [0],
            cuc_boc_vai_truoc: [0, 1, 2],
            cuc_boc_vai_sau: [0],
            holes_ban_ve: [0, 1, 2, 3],
            holes_kieu_dang: [0, 1, 2],
            holes_bac_tay: [0],
            threads_kieu_dang: [0, 1, 2],
            threads_bac_tay: [0],
            bong_ve_ao_vest: [0, 1, 2],
            elbow_patches: [0],
        },
        value: [
            {
                key: "default_lot_ao_vest_tren",
                fabric: "1645_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_arriba"]
            },
            {
                key: "default_lot_ao_vest_duoi",
                fabric: "1645_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_abajo+length_long"]
            },
            {
                key: "lot_ao_vest_tren",
                fabric: "linings/161_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_arriba"]
            },
            {
                key: "lot_ao_vest_duoi",
                fabric: "linings/161_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_abajo+length_long"]
            },
            {
                key: "lot_ao_vest_unlined_tren",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_arriba+unlined_v2"]
            },
            {
                key: "lot_ao_vest_unlined_duoi",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_abajo+length_long+unlined_v2"]
            },
            {
                key: "unlined_top_x",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_arriba+unlined_v2+x"]
            },
            {
                key: "unlined_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_arriba+unlined_v2"]
            },
            {
                key: "unlined_bottom",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["interior+espalda_abajo+length_long+unlined_v2"]
            },
            {
                key: "khan_tui_nguc",
                fabric: "empty/",
                prefix: '',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["handkerchief_recto"]
            },
            {
                key: "vong_co_sau_ao",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 37,
                element: ["neck"]
            },
            {
                key: "cuc_boc_vai_truoc",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["neck_single_breasted+buttons_2", "lapel_medium", "style_lapel_notch"]

            },
            {
                key: "cuc_boc_vai_sau",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 37,
                element: ["sleeves+buttons_4"]
            },
            {
                key: "holes_ban_ve",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["neck_single_breasted+buttons_2", "lapel_medium", "style_lapel_notch", "lapel"]
            },
            {
                key: "holes_kieu_dang",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["neck_single_breasted+buttons_2", "lapel_medium", "style_lapel_notch"]
            },
            {
                key: "holes_bac_tay",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["sleeves+buttons_4"]
            },
            {
                key: "threads_kieu_dang",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["neck_single_breasted+buttons_2", "lapel_medium", "style_lapel_notch"]
            },
            {
                key: "threads_bac_tay",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["sleeves+buttons_4"]
            },
            {
                key: "bong_ve_ao_vest",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 101,
                element: ["neck_single_breasted+buttons_2", "lapel_narrow", "style_lapel_notch"]
            },
            {
                key: "elbow_patches",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'jacket',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 37,
                element: ["elbow_patches"]
            },

        ]
    },
    shirt: {
        index: {
            pha_co_ao_somi: [0, 1, 2, 3],
            pha_co_sau_ao_somi: [0, 1],
            co_tay_ao_somi: [0, 1, 2],
            co_tay_ngan_ao_somi: [0, 1],
            co_tay_sau_ao_somi: [0, 1, 2],
            co_tay_ngan_sau_ao_somi: [0, 1],
            button_holes_collar_top: [0, 1, 2],
            button_holes_collar_bottom: [0, 1, 2],
            button_threads_collar_top: [0, 1, 2],
            button_threads_collar_bottom: [0, 1, 2],
            button_holes_cuffs: [0, 1],
            button_threads_cuffs: [0, 1],
            elbow_patches: [0, 1],
            cuc_ao_somi_tren: [0, 1, 2],
            cuc_ao_somi_duoi: [0, 1, 2],
            cuc_bac_tay: [0, 1],
            button_holes_pocket: [0],
            button_threads_pocket: [0],
            xep_ly_nguc: [0],
        },
        value: [
            {
                key: "pha_co_ao_somi",
                fabric: "1737_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["neck_contrast_full", "necklines_classic", "number_1", "button_close_standard"]
            },
            {
                key: "pha_co_sau_ao_somi",
                fabric: "1737_fabric/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["neck_contrast_outer", "necklines_1_button"]
            },
            {
                key: "co_tay_ao_somi",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["cuff_contrast_outer", "sleeves_long", "cuffs_classic"]
            },
            {
                key: "co_tay_ngan_ao_somi",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["cuff_contrast_outer", "sleeves_long"]
            },
            {
                key: "co_tay_sau_ao_somi",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["cuff_contrast_outer", "sleeves_long", "cuffs_style_squared"]
            },
            {
                key: "co_tay_ngan_sau_ao_somi",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["cuff_contrast_outer", "sleeves_long"]
            },
            {
                key: "button_holes_collar_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["necklines_classic", "number_1", "button_close_standard"]
            },
            {
                key: "button_holes_collar_bottom",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["fit_fit", "button_close_standard_", "inside"]
            },
            {
                key: "button_threads_collar_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["necklines_classic", "number_1", "button_close_standard"]
            },
            {
                key: "button_threads_collar_bottom",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["fit_fit", "button_close_standard_", "inside"]
            },
            {
                key: "button_holes_cuffs",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["sleeves_long", "cuffs_style_squared"]
            },
            {
                key: "button_threads_cuffs",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["sleeves_long", "cuffs_style_squared"]
            },
            {
                key: "elbow_patches",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["contrast", "elbow_patches"]
            },
            {
                key: "cuc_ao_somi_tren",
                fabric: "Botones/1/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["necklines_classic", "number_1", "button_close_standard"]
            },
            {
                key: "cuc_ao_somi_duoi",
                fabric: "Botones/1/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["fit_fit", "button_close_standard_", "inside"]
            },
            {
                key: "cuc_bac_tay",
                fabric: "Botones/1/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["sleeves_long", "cuffs_style_squared"]
            },
            {
                key: "button_holes_pocket",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["empty"]
            },
            {
                key: "button_threads_pocket",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["empty"]
            },
            {
                key: "xep_ly_nguc",
                fabric: "1737_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'shirt',
                opacity: 1,
                className: 'man_jacket',
                zIndex: 100,
                element: ["empty"]
            }
        ]
    },
    coat: {
        index: {
            default_lot_ao_mangto_tren: [0, 1, 2],
            lot_ao_mangto_tren: [0],
            lot_ao_mangto_unlined_tren: [0],
            unlined_top_x: [0],
            unlined_top: [0],
            pha_co_ao_mangto: [0, 1, 2, 3, 4, 5, 7],
            pha_co_sau_ao_mangto: [0, 1, 2],
            button_holes_collar_top: [0, 3],
            button_threads_collar_top: [0, 3],
            button_holes_collar_bottom: [0],
            button_threads_collar_bottom: [0],
            button_holes_cuffs: [0],
            elbow_patches: [0],
            vong_co_sau_ao: [0]
        },
        value: [
            {
                key: "default_lot_ao_mangto_tren",
                fabric: "1993_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["interior+arriba", "style_simple", "collar_classic", "fastening_trench"]
            },
            {
                key: "lot_ao_mangto_tren",
                fabric: "linings/163_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["interior+espalda"]
            },
            {
                key: "lot_ao_mangto_unlined_tren",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["especial+interior+espalda_unlined"]
            },
            {
                key: "unlined_top_x",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["interior+espalda_unlined+x"]
            },
            {
                key: "unlined_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["interior+espalda_unlined"]
            },
            {
                key: "pha_co_ao_mangto",
                fabric: "1993_fabric/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["top", "style_simple", "collar_flap", "lapel_lenght_long", "lapel_wide_wide", "lapel_style_notched", "lenght_short", "fastening_boton_standard"]
            },
            {
                key: "pha_co_sau_ao_mangto",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["top", "collar_classic", "flap"]
            },
            {
                key: "button_holes_collar_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["buttons", "style_simple", "collar_flap", "lapel_lenght_long", "lapel_wide_wide", "lapel_style_notched", "lenght_short", "fastening_boton_standard"]
            },
            {
                key: "button_holes_collar_bottom",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["empty", "style_crossed", "collar_flap", "lenght_short", "fastening_boton_standard"]
            },
            {
                key: "button_threads_collar_top",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["buttons", "style_simple", "collar_flap", "lapel_lenght_long", "lapel_wide_wide", "lapel_style_notched", "lenght_short", "fastening_boton_standard"]
            },
            {
                key: "button_threads_collar_bottom",
                fabric: "empty/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["empty", "style_crossed", "collar_flap", "lenght_short", "fastening_boton_standard"]
            },
            {
                key: "button_holes_cuffs",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["empty"]
            },
            {
                key: "elbow_patches",
                fabric: "empty/",
                prefix: 'back/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["elbow_patches"]
            },
            {
                key: "vong_co_sau_ao",
                fabric: "back/",
                prefix: 'front/',
                suffix: '.png',
                ingredient: 'coat_2',
                opacity: 1,
                className: 'man_coat',
                zIndex: 100,
                element: ["collar_neck_open"]
            }
        ]
    }
}
export default initPropetiesExtra;